// This script restructures the build output for Vercel deployment
//
// Strategy:
// - dist/static/ → frontend static files (served by Vercel via outputDirectory)
// - api/index.js → serverless function (ESM, auto-detected by Vercel)
//
// The function imports the ESM server bundle and creates the Express app.
// Static files and SPA fallback are handled by Vercel's rewrites.

const fs = require("fs");
const path = require("path");

function copyDirSync(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

const rootDir = path.resolve(__dirname, "..");
const distDir = path.resolve(rootDir, "dist");
const publicDir = path.resolve(distDir, "public");
const staticDir = path.resolve(distDir, "static");

// 1. Create dist/static/ from vite build output
console.log("[Vercel Build] Creating dist/static/...");
if (fs.existsSync(staticDir)) {
  fs.rmSync(staticDir, { recursive: true });
}
fs.mkdirSync(staticDir, { recursive: true });

if (fs.existsSync(publicDir)) {
  copyDirSync(publicDir, staticDir);
  console.log("[Vercel Build] Copied dist/public → dist/static");
} else {
  console.error("[Vercel Build] ERROR: dist/public not found!");
  process.exit(1);
}

// 2. Copy the ESM server bundle into the api/ directory
// So the function can import it directly
console.log("[Vercel Build] Preparing server bundle...");
const serverBundle = path.resolve(distDir, "server", "index.mjs");
if (!fs.existsSync(serverBundle)) {
  console.error("[Vercel Build] ERROR: dist/server/index.mjs not found!");
  process.exit(1);
}

const rootApiDir = path.resolve(rootDir, "api");
if (!fs.existsSync(rootApiDir)) {
  fs.mkdirSync(rootApiDir, { recursive: true });
}

// Copy the ESM bundle to api/server.mjs
const serverDest = path.resolve(rootApiDir, "server.mjs");
fs.copyFileSync(serverBundle, serverDest);
console.log("[Vercel Build] Copied server bundle to api/server.mjs");

// 3. Generate the thin ESM wrapper
const apiCode = `// Vercel serverless function - API only (static files served by Vercel CDN)
// Generated by vercel-build.cjs

import { createApp } from "./server.mjs";

// Create and export the Express app
const app = createApp();

// API fallback - return JSON error for unknown API routes
app.use(function(_req, res) {
  res.status(404).json({ error: "API endpoint not found" });
});

export default app;
`;

fs.writeFileSync(path.resolve(rootApiDir, "index.js"), apiCode);
console.log("[Vercel Build] Generated api/index.js (thin ESM wrapper)");

// 4. Clean up
const oldDirs = ["public", "server", "functions"];
for (const dir of oldDirs) {
  const oldPath = path.resolve(distDir, dir);
  if (fs.existsSync(oldPath)) {
    fs.rmSync(oldPath, { recursive: true });
    console.log(`[Vercel Build] Cleaned up dist/${dir}`);
  }
}

// 5. Summary
console.log("\n[Vercel Build] Output structure:");
console.log("  dist/static/ →", fs.readdirSync(staticDir).join(", "));
console.log("  api/index.js →", fs.existsSync(path.resolve(rootApiDir, "index.js")) ? "YES" : "NO");
console.log("  api/server.mjs →", fs.existsSync(serverDest) ? "YES" : "NO");

console.log("\n[Vercel Build] Done!");
