// This script restructures the build output for Vercel deployment
//
// Strategy:
// - dist/static/ → frontend static files (served by Vercel via outputDirectory)
// - api/index.js → serverless function (ESM, auto-detected by Vercel)
//
// The function only handles API requests (/api/*).
// Static files and SPA fallback are handled by Vercel's rewrites.

const fs = require("fs");
const path = require("path");

function copyDirSync(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

const rootDir = path.resolve(__dirname, "..");
const distDir = path.resolve(rootDir, "dist");
const publicDir = path.resolve(distDir, "public");
const staticDir = path.resolve(distDir, "static");

// 1. Create dist/static/ from vite build output
console.log("[Vercel Build] Creating dist/static/...");
if (fs.existsSync(staticDir)) {
  fs.rmSync(staticDir, { recursive: true });
}
fs.mkdirSync(staticDir, { recursive: true });

if (fs.existsSync(publicDir)) {
  copyDirSync(publicDir, staticDir);
  console.log("[Vercel Build] Copied dist/public → dist/static");
} else {
  console.error("[Vercel Build] ERROR: dist/public not found!");
  process.exit(1);
}

// 2. Generate the serverless function
console.log("[Vercel Build] Generating serverless function...");
const serverBundle = path.resolve(distDir, "server", "index.cjs");
if (!fs.existsSync(serverBundle)) {
  console.error("[Vercel Build] ERROR: dist/server/index.cjs not found!");
  process.exit(1);
}

const serverCode = fs.readFileSync(serverBundle, "utf8");

const apiCode = `// Vercel serverless function - API only (static files served by Vercel CDN)
// Generated by vercel-build.cjs

import path from "path";
import fs from "fs";
import { createRequire } from "module";
import { fileURLToPath } from "url";
import express from "express";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);

// Set environment
process.env.VERCEL = "1";
process.env.NODE_ENV = "production";

// --- Server Bundle (inlined) ---
// The bundle uses require() which works via createRequire above.
// We replace module.exports with a local variable to make it ESM-compatible.
var __module_exports = {};
var module = { exports: __module_exports };

${serverCode.replace(/module\.exports/g, "__module_exports")}
// --- End Server Bundle ---

// Get the Express app from the bundle
// The server bundle exports createApp() function. We call it directly.
var __app;
try {
  // Try to get createApp from the bundle exports
  if (typeof __module_exports === 'function' || (__module_exports && __module_exports.handle)) {
    __app = __module_exports;
  } else if (__module_exports && __module_exports._router) {
    __app = __module_exports;
  } else if (typeof createApp === 'function') {
    __app = createApp();
  }
} catch(e) {
  console.warn("[Vercel] Could not get app:", e.message);
}

// Fallback
if (!__app) {
  console.log("[Vercel] Creating fallback app");
  __app = express();
  __app.use(express.json({ limit: "50mb" }));
  __app.use(express.urlencoded({ limit: "50mb", extended: true }));
}

// API fallback - return JSON error for unknown API routes
__app.use(function(_req, res) {
  res.status(404).json({ error: "API endpoint not found" });
});

// Export for Vercel
export default __app;
`;

// Write to api/index.js in project root
const rootApiDir = path.resolve(rootDir, "api");
if (!fs.existsSync(rootApiDir)) {
  fs.mkdirSync(rootApiDir, { recursive: true });
}
fs.writeFileSync(path.resolve(rootApiDir, "index.js"), apiCode);
console.log("[Vercel Build] Generated api/index.js (ESM-compatible)");

// 3. Clean up
const oldDirs = ["public", "server", "functions"];
for (const dir of oldDirs) {
  const oldPath = path.resolve(distDir, dir);
  if (fs.existsSync(oldPath)) {
    fs.rmSync(oldPath, { recursive: true });
    console.log(`[Vercel Build] Cleaned up dist/${dir}`);
  }
}

// 4. Summary
console.log("\n[Vercel Build] Output structure:");
console.log("  dist/static/ →", fs.readdirSync(staticDir).join(", "));
console.log("  api/index.js →", fs.existsSync(path.resolve(rootApiDir, "index.js")) ? "YES" : "NO");

console.log("\n[Vercel Build] Done!");
