// This script restructures the build output for Vercel deployment
// 
// Vercel builds config:
//   - dist/static/** → @vercel/static (served as static files)
//   - dist/functions/api/index.cjs → @vercel/node (serverless function)
//
// The function needs its own copy of static files because Vercel's serverless
// functions run in an isolated filesystem.
//
// Routes: all requests → dist/functions/api/index.cjs
//   - API routes handled by tRPC
//   - Static files served by express.static
//   - SPA fallback serves index.html

const fs = require("fs");
const path = require("path");

function copyDirSync(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

const rootDir = path.resolve(__dirname, "..");
const distDir = path.resolve(rootDir, "dist");
const publicDir = path.resolve(distDir, "public");
const staticDir = path.resolve(distDir, "static");
const functionsDir = path.resolve(distDir, "functions", "api");
const fnStaticDir = path.resolve(functionsDir, "static");

// 1. Create dist/static/ for Vercel's @vercel/static build
console.log("[Vercel Build] Creating dist/static/ for Vercel static build...");
if (fs.existsSync(staticDir)) {
  fs.rmSync(staticDir, { recursive: true });
}
fs.mkdirSync(staticDir, { recursive: true });

if (fs.existsSync(publicDir)) {
  copyDirSync(publicDir, staticDir);
  console.log("[Vercel Build] Copied dist/public → dist/static");
} else {
  console.error("[Vercel Build] ERROR: dist/public not found!");
  process.exit(1);
}

// 2. Create functions directory
console.log("[Vercel Build] Creating functions directory...");
fs.mkdirSync(functionsDir, { recursive: true });

// 3. Copy static files into the function directory (function needs its own copy)
console.log("[Vercel Build] Copying static files into function directory...");
if (fs.existsSync(fnStaticDir)) {
  fs.rmSync(fnStaticDir, { recursive: true });
}
fs.mkdirSync(fnStaticDir, { recursive: true });
copyDirSync(publicDir, fnStaticDir);
console.log("[Vercel Build] Copied static files to dist/functions/api/static/");

// 4. Generate the serverless function
console.log("[Vercel Build] Generating serverless function...");
const serverBundle = path.resolve(distDir, "server", "index.cjs");
if (!fs.existsSync(serverBundle)) {
  console.error("[Vercel Build] ERROR: dist/server/index.cjs not found!");
  process.exit(1);
}

const serverCode = fs.readFileSync(serverBundle, "utf8");
const indexHtmlPath = path.resolve(fnStaticDir, "index.html");
const hasIndexHtml = fs.existsSync(indexHtmlPath);

// The generated function serves static files from __dirname + "/static"
// and uses the bundle's serveStatic which looks for __dirname + "/public"
const publicLink = path.resolve(functionsDir, "public");
// Create a "public" directory with copies of static files
// The bundle's serveStatic looks for __dirname + "/public"
// We create it as a real directory (not symlink) for Vercel compatibility
if (fs.existsSync(publicLink)) {
  fs.rmSync(publicLink, { recursive: true });
}
fs.mkdirSync(publicLink, { recursive: true });
copyDirSync(fnStaticDir, publicLink);
console.log("[Vercel Build] Copied static files to dist/functions/api/public/ (for bundle's serveStatic)");

const apiCode = `// Vercel serverless function - generated by vercel-build.cjs
// Serves both frontend (static files + SPA) and backend (tRPC API)

var __hasPublic = ${hasIndexHtml ? "true" : "false"};

// Set environment
process.env.VERCEL = "1";
process.env.NODE_ENV = "production";

// --- Server Bundle (inlined) ---
${serverCode}
// --- End Server Bundle ---

var __path = require("path");
var __fs = require("fs");
var __express = require("express");

// Get the Express app from the CJS bundle
var __app;
try {
  if (module.exports && module.exports._router) {
    __app = module.exports;
  } else if (typeof module.exports === 'function' || (module.exports && module.exports.handle)) {
    __app = module.exports;
  }
} catch(e) {
  console.warn("[Vercel] Could not get app from module.exports:", e.message);
}

// Fallback
if (!__app) {
  console.log("[Vercel] Creating fallback app");
  __app = __express();
  __app.use(__express.json({ limit: "50mb" }));
  __app.use(__express.urlencoded({ limit: "50mb", extended: true }));
}

// Add static file serving from the function's own static directory
// (in case the bundle's serveStatic doesn't find them)
var __staticPath = __path.resolve(__dirname, "static");
if (__fs.existsSync(__staticPath)) {
  __app.use(__express.static(__staticPath));
  console.log("[Vercel] Serving static files from:", __staticPath);
}

// SPA fallback
__app.get("*", function(_req, res) {
  if (__hasPublic) {
    var indexPath = __path.resolve(__staticPath, "index.html");
    if (__fs.existsSync(indexPath)) {
      return res.sendFile(indexPath);
    }
  }
  res.status(404).send("Not Found");
});

// Export for Vercel
module.exports = __app;
`;

fs.writeFileSync(path.resolve(functionsDir, "index.cjs"), apiCode);
console.log("[Vercel Build] Generated dist/functions/api/index.cjs");

// 5. Clean up old directories
const oldDirs = ["public", "server"];
for (const dir of oldDirs) {
  const oldPath = path.resolve(distDir, dir);
  if (fs.existsSync(oldPath)) {
    fs.rmSync(oldPath, { recursive: true });
    console.log(`[Vercel Build] Cleaned up dist/${dir}`);
  }
}

// 6. Summary
console.log("\n[Vercel Build] Output structure:");
console.log("  dist/static/ → static files (for @vercel/static)");
const fnEntries = fs.readdirSync(functionsDir);
console.log("  dist/functions/api/ →", fnEntries.join(", "));
console.log("  index.html exists:", hasIndexHtml);

console.log("\n[Vercel Build] Done!");
