// Vercel serverless function - API handler
// Generated by vercel-build.cjs
// This handles all /api/* requests.
// Static files and SPA fallback are handled by Vercel's rewrites.

import { createApp } from "./server.mjs";

// Create and export the Express app
const app = createApp();

// API fallback - return JSON error for unknown API routes
app.use(function(_req, res) {
  res.status(404).json({ error: "API endpoint not found" });
});

export default app;
