// Vercel serverless function - API only (static files served by Vercel CDN)
// Generated by vercel-build.cjs

import { createApp } from "./server.mjs";

// Create and export the Express app
const app = createApp();

// API fallback - return JSON error for unknown API routes
app.use(function(_req, res) {
  res.status(404).json({ error: "API endpoint not found" });
});

export default app;
